---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "radarr"

patchesStrategicMerge:
  - "deployment-patch.yml"
  - "pvc-config.yml"

resources:
  - "../../base"
