---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "homebridge"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homebridge"
  strategy:
    # you need to recreate so that the RWO PVC works
    type: "Recreate"
  template:
    spec:
      # you need to use the host's networking stack to publish mDNS packets.
      hostNetwork: true
      containers:
        - name: "homebridge"
          image: "oznu/homebridge:2022-11-14"
          env:
            - name: "ENABLE_AVAHI"
              value: "0"
            - name: "TZ"
              value: "America/Los_Angeles"
          volumeMounts:
            - $patch: "replace"
            - mountPath: "/homebridge"
              name: "homebridge-pvc"
      volumes:
        - $patch: "replace"
        - name: "homebridge-pvc"
          persistentVolumeClaim:
            claimName: "homebridge-pvc"
