---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"
commonLabels:
  app: "homebridge"

resources:
  - "../../base"
  - "pvc.yml"

patchesStrategicMerge:
  - "deployment-patch-provisioning.yml"
  - "persist-pvc-patch.yml"

configMapGenerator:
  []
  # https://vault.inthemainfra.me/ui/vault/secrets/kubernetes/show/homebridge/overlays/antioch/homebridge-config/config.json
  # - name: "homebridge-config"
  #   files:
  #     - "config.json=homebridge-config/config.secret"
  # - name: "homebridge-plugins"
  #   files:
  #     - "homebridge-config/package.json"
