---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"
commonLabels:
  app: "homebridge"

resources:
  - "../../base"
  - "pvc.yml"

patches:
  - path: "deployment-patch-provisioning.yml"
    target:
      kind: "Deployment"

configMapGenerator:
  []
  # https://vault.inthemainfra.me/ui/vault/secrets/kubernetes/kv/homebridge%2Foverlays%2Fantioch%2Fhomebridge-config
  # - name: "homebridge-config"
  #   files:
  #     - "config.json=homebridge-config/config.secret"
  # - name: "homebridge-plugins"
  #   files:
  #     - "homebridge-config/package.json"
