---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../base"
  - "media-pv.yml"

patches:
  - path: "pvc-patch.yml"
    target:
      kind: "PersistentVolumeClaim"
      name: "media-pvc"
