---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "metrics"
commonLabels:
  app: "loki"

resources:
  - "../../base"

patchesStrategicMerge:
  - "pvc.yml"
  - "service-patch.yml"
