---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "loki-data-pvc"
spec:
  resources:
    requests:
      storage: "25Gi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "ceph-filesystem"
