---
# https://github.com/tailscale/tailscale/blob/main/docs/k8s/role.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "tailscale"
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]

---
# https://github.com/tailscale/tailscale/blob/main/docs/k8s/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: "tailscale"
subjects:
  - kind: "ServiceAccount"
    name: "tailscale"
roleRef:
  kind: "Role"
  name: "tailscale"
  apiGroup: "rbac.authorization.k8s.io"

---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "tailscale"
