---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "default"
commonLabels:
  app: "vaultwarden"

resources:
  - "deployment.yml"
  - "service.yml"
  - "pvc.yml"

configMapGenerator:
  - name: "vaultwarden-config"
    literals:
      - "DOMAIN=https://passwords.inthemainfra.me"
      - "SIGNUPS_ALLOWED=false"
      - "PASSWORD_HINTS_ALLOWED=false"
      - "IP_HEADER=CF-Connecting-IP"  # cloudflare specific
      - "LOG_TIMESTAMP_FORMAT=%+"
      - "_ENABLE_SMTP=false"
      - "PUSH_ENABLED=true"

# https://vault.inthemainfra.me/ui/vault/secrets/kubernetes/kv/vaultwarden/details
secretGenerator:
  - name: "vaultwarden-secrets"
    envs:
      - "vaultwarden.secret"
