---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "vaultwarden-data"
spec:
  resources:
    requests:
      storage: "256Mi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
