---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../base"

patches:
  - path: "pvc-patch.yml"
    target:
      kind: "PersistentVolumeClaim"
  - path: "resource-quotas-patch.yml"
    target:
      kind: "ResourceQuota"
