---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "media-pvc"
  namespace: "media"
spec:
  resources:
    requests:
      storage: "13Ti"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "topolvm-hdd-ext4"
