---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "media-pvc"
  namespace: "media"
spec:
  resources:
    requests:
      storage: "10Ti"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteMany"
  storageClassName: "ceph-filesystem"
