---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "pihole"
commonLabels:
  app: "pihole"
resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
  - "pvc.yml"
