---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "plex"
resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
  - "plex-config-pvc.yml"
