---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "plex-config-pvc"
spec:
  resources:
    requests:
      storage: "128Gi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "csi-rbd-sc"
