---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
labels:
  - pairs:
      app: "epaper-image-display-server"
    includeSelectors: true
resources:
  - "deployment.yml"
  - "ingress.yml"
  - "service.yml"
