---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
labels:
  - includeSelectors: true
    pairs:
      app: "samba"

patches:
  - path: "deployment-patch.yml"
    target:
      name: "samba"
      kind: "Deployment"

resources:
  - "../../base"

configMapGenerator:
  - name: "sambacc-configmap"
    behavior: "replace"
    files:
      - "sambacc-configmap.json"
