---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "samba"

patches:
  - path: "deployment-patch.yml"
    target:
      name: "samba"
      kind: "Deployment"

resources:
  - "../../base"
