{
 "title": "Kubernetes / System / CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server.",
 "tags": [
  "dns",
  "coredns",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(coredns_build_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "max delay"
    }
   ]
  },
  {
   "title": "Requests/s (by pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests/s (by Protocol)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\"}[1m])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Denial Cache Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{type=\"denial\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Success Cache Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{type=\"success\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"coredns\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cache (Hits)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{type=\"success\",cluster=\"$cluster\"}[1m]))",
     "legendFormat": "hits: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{type=\"denial\",cluster=\"$cluster\"}[1m]))",
     "legendFormat": "hits: denial"
    }
   ]
  },
  {
   "title": "Cache (Misses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_misses_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$cluster\"}[1m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Requests w/ DNSSEC OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_do_requests_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\"}[1m])) by (le,proto))",
     "legendFormat": "{{proto}}:99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\"}[1m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\"}[1m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests (size,tcp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Responses (size, udp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\"}[1m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\"}[1m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\"}[1m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (size, tcp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\"}[1m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\"}[1m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\"}[1m])) by (le, proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  { "title": "Forward requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Forward: Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{cluster=\"$cluster\"}[1m])) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Forward: Responses (by rcode)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{cluster=\"$cluster\"}[1m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Forward: Cache (Hits)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_conn_cache_hits_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "hits: success"
    }
   ]
  },
  {
   "title": "Forward: Cache (Misses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_conn_cache_misses_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Forward: Request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(coredns_forward_request_duration_seconds_bucket{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "max delay"
    }
   ]
  }
 ]
}