---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "metrics"
commonLabels:
  app: "loki"
resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
  - "pvc.yml"
