---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: csi-rbd-secret
    volume.kubernetes.io/provisioner-deletion-secret-namespace: default
  finalizers:
    - external-provisioner.volume.kubernetes.io/finalizer
    - kubernetes.io/pv-protection
  name: loki-data-pvc
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-rbd-sc
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: loki-data-pvc
    namespace: metrics
  csi:
    controllerExpandSecretRef:
      name: csi-rbd-secret
      namespace: default
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: default
    volumeAttributes:
      clusterID: a05891f1-8170-4f0b-bcc0-37ccbfdf1f69
      imageFeatures: layering
      imageName: csi-vol-f3a932f6-09c2-4706-bff6-11a5c8ed5b2c
      journalPool: kubernetes
      pool: kubernetes
      storage.kubernetes.io/csiProvisionerIdentity: 1705186192112-9602-rbd.csi.ceph.com
      thickProvision: 'false'
    volumeHandle: 0001-0024-a05891f1-8170-4f0b-bcc0-37ccbfdf1f69-0000000000000005-f3a932f6-09c2-4706-bff6-11a5c8ed5b2c
