{
 "title": "Transmission",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "torrent",
    "label": "torrent",
    "query": {
     "query": "label_values(transmission_torrent_added, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Downloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(transmission_torrent_download_bytes{name=~\"$torrent\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upload bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(transmission_torrent_upload_bytes{name=~\"$torrent\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(transmission_torrent_done{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_ratio{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_leechers{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_seeders{name=~\"$torrent\"}) by (name)"
    }
   ]
  }
 ]
}