---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"
commonLabels:
  app: "esp8266-nowplaying"
resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
  - "pvc.yml"

secretGenerator:
  - name: "esp8266-nowplaying-spotify-credentials"
    envs:
      - "esp8266-nowplaying-spotify-credentials.secret"
