---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sonarr"
spec:
  selector:
    matchLabels:
      app: "sonarr"
  template:
    spec:
      containers:
        - name: "sonarr"
          env:
            - name: "TZ"
              value: "America/Los_Angeles"
