---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "rclone-gdrive-sync"

patches:
  - path: "cronjob-patch.yml"
    target:
      kind: "CronJob"
      name: "rclone-gdrive-sync"

resources:
  - "../../base"
