---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "rclone-gdrive-sync"
resources:
  - "cronjob.yml"

# https://vault.inthemainfra.me/ui/vault/secrets/rclone-google-drive/kv/oauth2%2Frclone-google-drive/details?version=2
secretGenerator:
  - name: "rclone-gdrive-sync-credentials"
    envs:
      - "oauth_creds.secret"

# https://rclone.org/drive/
configMapGenerator:
  - name: "rclone-gdrive-sync-config"
    files:
      - "rclone.conf"
