---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "transmission-openvpn"

resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
  - "vmservicescrape.yml"
