---
apiVersion: "operator.victoriametrics.com/v1beta1"
kind: "VMServiceScrape"
metadata:
  name: "torrent-export"
spec:
  namespaceSelector:
    matchNames:
      - "media"
  selector:
    matchLabels:
      app: "transmission-openvpn"
  endpoints:
    - port: "torrent-export"
      path: "/metrics"
      interval: "5s"
