---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "default"
labels:
  - pairs:
      app: "wolf"
    includeSelectors: true

resources:
  - "../../base"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
  - path: "pvc-patch.yml"
    target:
      kind: "PersistentVolumeClaim"
      name: "wolf-pvc"
