---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"
commonLabels:
  app: "esp8266-nowplaying"

resources:
  - "../../base"

patches:
  - path: "pvc-patch.yml"
    target:
      kind: "PersistentVolumeClaim"
      name: "esp8266-nowplaying-spotify-cache"
