---
# https://github.com/cloudflare/argo-tunnel-examples/blob/master/named-tunnel-k8s/cloudflared.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cloudflared"
spec:
  selector:
    matchLabels:
      app: "cloudflared"
  template:
    metadata:
      labels:
        app: "cloudflared"
    spec:
      containers:
        - name: "cloudflared"
          image: "cloudflare/cloudflared:latest"
          args:
            - "tunnel"
            - "--config"
            - "/etc/cloudflared/config/cloudflared-configmap.yml"
            - "run"
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only
              # if it has an active connection to the edge.
              path: "/ready"
              port: "cloudflared"
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 2000
              name: "cloudflared"
          volumeMounts:
            - mountPath: "/etc/cloudflared/config"
              name: "config"
              readOnly: true
            - mountPath: "/etc/cloudflared/creds"
              name: "cloudflared-token"
              readOnly: true
      volumes:
        - name: "cloudflared-token"
          secret:
            secretName: "cloudflared-token"
        - name: "config"
          configMap:
            name: "cloudflared-configmap"
