apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
labels:
  - includeSelectors: true
    pairs:
      app: "readarr"
resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
  - "pvc.yml"
