---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "komga"

resources:
  - "../../base"
  - "komga-config-pv.yml"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
