---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "grafana"
spec:
  selector:
    matchLabels:
      app: "grafana"
  template:
    metadata:
      labels:
        app: "grafana"
    spec:
      containers:
        - name: "grafana"
          image: "grafana/grafana:9.2.4"
          volumeMounts:
            - mountPath: "/etc/grafana/grafana.ini"
              name: "grafana-configmap"
              subPath: "grafana.ini"
            - mountPath: "/etc/grafana/provisioning"
              name: "grafana-provisioning"
      volumes:
        - name: "grafana-configmap"
          configMap:
            name: "grafana-config"
        - name: "grafana-provisioning"
          configMap:
            name: "grafana-provisioning"
            items:
              - key: "influxdb.yml"
                path: "datasources/influxdb.yml"
              - key: "tempo.yml"
                path: "datasources/tempo.yml"
