---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "komga-config"
spec:
  resources:
    requests:
      storage: "50Mi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "csi-rbd-sc"
