---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "prowlarr"

resources:
  - "../../base"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
  - path: "pvc-config.yml"
    target:
      kind: "PersistentVolumeClaim"
      name: "prowlarr-config"
