---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "prowlarr-config"
spec:
  resources:
    requests:
      storage: "64Mi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "topolvm-nvme-ext4"
