---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "metrics"
commonLabels:
  app: "tempo"

resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"

configMapGenerator:
  - name: "tempo-config"
    files:
      - "tempo.yml"
