---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "pihole"
commonLabels:
  app: "pihole"

resources:
  - "../../base"

patches:
  - path: "pvc-patch.yml"
    target:
      name: "pihole-data"
      kind: "PersistentVolumeClaim"

  - path: "pvc-patch.yml"
    target:
      name: "pihole-dnsmasq"
      kind: "PersistentVolumeClaim"
