---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "homebridge-persist-pvc"
spec:
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "128Mi"
  storageClassName: "csi-rbd-sc"
