---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"
commonLabels:
  app: "homebridge"

resources:
  - "../../base"
  - "homebridge-persist-pv.yml"
  - "homebridge-persist-pvc.yml"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"

configMapGenerator:
  # https://vault.inthemainfra.me/ui/vault/secrets/kubernetes/show/homebridge/overlays/chicago/homebridge-config/config.json
  - name: "homebridge-config"
    files:
      - "config.json=homebridge-config/config.secret"
  - name: "homebridge-plugins"
    files:
      - "homebridge-config/package.json"
