---
- path: "/spec/template/spec/containers/0/env/-"
  op: "add"
  value:
    name: "TZ"
    value: "America/Los_Angeles"

- path: "/spec/template/spec/nodeName"
  op: "replace"
  value: "k3os-20356"
