---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "radarr"

resources:
  - "radarr-config-pv.yml"
  - "../../base"

patches:
  - path: "deployment-patch.yml"
    target:
      name: "radarr"
      kind: "Deployment"
