---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "default"
commonLabels:
  app: "vaultwarden"

resources:
  - "../../base"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
