---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "plex"
spec:
  selector:
    matchLabels:
      app: "plex"
  template:
    metadata:
      labels:
        app: "plex"
    spec:
      # for UDP (bonjour, gday)
      hostNetwork: true
      containers:
        - name: "plex"
          image: "linuxserver/plex:latest"
          imagePullPolicy: "Always"
          env:
            - name: "PLEX_MEDIA_SERVER_USE_SYSLOG"
              value: "true"
          volumeMounts:
            - mountPath: "/config"
              name: "plex-config-pvc"
