---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "plex"

resources:
  - "../../base"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
      name: "plex"
  - path: "intel-quicksync-volume-patch.yml"
    target:
      kind: "Deployment"
      name: "plex"
  - path: "plex-config-pvc-patch.yml"
    target:
      kind: "PersistentVolumeClaim"
      name: "plex-config-pvc"
