---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "plex"

resources:
  - "../../base"

patchesStrategicMerge:
  - "deployment-preferences.yml"
  - "plex-config-pvc-patch.yml"
