---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "plex-config-pvc"
spec:
  resources:
    requests:
      storage: "100Gi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "topolvm-nvme-ext4"
