---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  namespace: "metrics"
  name: "default-limits"
spec:
  limits:
    - defaultRequest:
        memory: "32Mi"
        cpu: "32m"
      type: "Container"
