---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "csi-rbdplugin-provisioner"
  namespace: "default"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "csi-rbdplugin-provisioner"
  template:
    metadata:
      labels:
        app: "csi-rbdplugin-provisioner"
    spec:
      containers:
        - name: "csi-rbdplugin-controller"
          image: "quay.io/cephcsi/cephcsi:canary"
          args:
            - "--type=controller"
            # we're overriding the --v=5 from upstream to --v=1 to reduce spam
            # https://github.com/kubernetes/kubernetes/issues/34594
            - "--v=1"
            - "--drivername=rbd.csi.ceph.com"
            - "--drivernamespace=$(DRIVER_NAMESPACE)"
            - "--setmetadata=true"
