---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../base"

configMapGenerator:
  # https://vault.inthemainfra.me/ui/vault/secrets/chicago/kv/proxmox%2Fceph
  - name: "ceph-csi-config"
    behavior: "replace"
    files:
      - "config.json=ceph-csi-config.json"

secretGenerator:
  # https://vault.inthemainfra.me/ui/vault/secrets/chicago/kv/proxmox%2Fceph
  - name: "csi-rbd-secret"
    behavior: "merge"
    files:
      - "userKey=csi-rbd-userkey.secret"

patches:
  # https://vault.inthemainfra.me/ui/vault/secrets/chicago/kv/proxmox%2Fceph
  - path: "csi-rbdplugin-storage-class-patch.yml"
    target:
      kind: "StorageClass"
      name: "csi-rbd-sc"
  - path: "csi-rbdplugin-provisioner-patch.yml"
    target:
      kind: "Deployment"
      name: "csi-rbdplugin-provisioner"
