---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "victoriametrics-data-pvc"
spec:
  resources:
    requests:
      storage: "10Gi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "csi-rbd-sc"
