---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "sunshine-pvc"
spec:
  resources:
    requests:
      storage: "64Gi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
