---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "plex"
spec:
  selector:
    matchLabels:
      app: "plex"
  template:
    metadata:
      labels:
        app: "plex"
    spec:
      nodeName: "k3os-20356"
      containers:
        - name: "plex"
          image: "linuxserver/plex:latest"
          env:
            - name: "PLEX_MEDIA_SERVER_USE_SYSLOG"
              value: "true"
            # - name: "PLEX_CLAIM"
            #   value: "claim-byGN8ucJGHqGfx2xgbhT"
          volumeMounts:
            - mountPath: "/config"
              name: "plex-config-pvc"
            # - mountPath: "/config/Library/Application Support/Plex Media Server/Preferences.xml"
            #   name: "plex-preferences-xml"
            #   subPath: "Preferences.xml"
      # volumes:
      #   - name: "plex-preferences-xml"
      #     configMap:
      #       name: "plex-preferences-xml"
