---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "plex"

resources:
  - "../../base"
  # - "plex-config-pv.yml"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
      name: "plex"
  - path: "hardware-transcode-volume-patch.yml"
    target:
      kind: "Deployment"
      name: "plex"

# configMapGenerator:
#   - name: "plex-preferences-xml"
#     files:
#       - "Preferences.xml=Preferences.xml.secret"
