---
- path: "/spec/template/spec/containers/0/envFrom"
  op: "replace"
  value:
    - configMapRef:
        name: "transmission-config"
    - secretRef:
        name: "vpn-credentials"

- path: "/spec/template/spec/nodeName"
  op: "replace"
  value: "k3s-node-2"
