{
 "title": "Modem",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Upstream Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "modem_upstream_channel_frequency",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "Lock status",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "modem_upstream_channel_lock_status",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "modem_upstream_channel_power",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  { "title": "Downstream Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_downstream_channel_frequency",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "modem_downstream_channel_snr",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "modem_downstream_channel_power",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "Lock status",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "modem_downstream_channel_lock_status",
     "legendFormat": "{{channel_id}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "corrected + uncorrectables",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "deriv(modem_downstream_channel_corrected[$__interval])",
     "legendFormat": "{{channel_id}} - {{modulation}} (corrected)"
    },
    {
     "expr": "deriv(modem_downstream_channel_uncorrectables[$__interval])",
     "legendFormat": "{{channel_id}} - {{modulation}} (uncorrected)"
    }
   ]
  }
 ]
}