---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"

labels:
  - includeSelectors: true
    pairs:
      app: "omada-controller"

resources:
  - "pvc.yml"
  - "deployment.yml"
  - "service.yml"
  # - "ingress.yml"
