---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "default"
commonLabels:
  app: "cloudflared"

resources:
  - "../base"

configMapGenerator:
  - name: "cloudflared-configmap"
    files:
      - "cloudflared-configmap.yml"

secretGenerator:
  - name: "cloudflared-token"
    files:
      - "cloudflared-token.secret"
