---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "samba"

resources:
  - "deployment.yml"
  - "service.yml"

configMapGenerator:
  - name: "sambacc-configmap"
    files:
      - "sambacc-configmap.json"
