---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "samba"
spec:
  selector:
    app: "samba"
  type: "LoadBalancer"
  ports:
    - port: 445
      name: "samba-tcp"
      protocol: "TCP"
      nodePort: 30001
