---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "metrics"
commonLabels:
  app: "grafana"
resources:
  - "../../base"
  - "grafana-dashboards-pvc.yml"

patchesStrategicMerge:
  - "deployment-patch-provisioning.yml"

configMapGenerator:
  - name: "grafana-config"
    files:
      - "grafana.ini"
  - name: "grafana-provisioning"
    files:
      - "provisioning/datasources/victoriametrics.yml"
      - "provisioning/datasources/loki.yml"
      - "provisioning/dashboards/dashboard-provisioning.yml"
