---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "media"
commonLabels:
  app: "sonarr"

resources:
  - "sonarr-config-pv.yml"
  - "../../base"

patches:
  - path: "deployment-patch.yml"
    target:
      kind: "Deployment"
