---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: csi-rbd-secret
    volume.kubernetes.io/provisioner-deletion-secret-namespace: default
  finalizers:
    - external-provisioner.volume.kubernetes.io/finalizer
    - kubernetes.io/pv-protection
  name: sonarr-config
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-rbd-sc
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sonarr-config
    namespace: media
  csi:
    controllerExpandSecretRef:
      name: csi-rbd-secret
      namespace: default
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: default
    volumeAttributes:
      clusterID: a05891f1-8170-4f0b-bcc0-37ccbfdf1f69
      imageFeatures: layering
      imageName: csi-vol-4267fd51-a03e-4182-94fe-72436d4ac24d
      journalPool: kubernetes
      pool: kubernetes
      storage.kubernetes.io/csiProvisionerIdentity: 1705186192112-9602-rbd.csi.ceph.com
      thickProvision: 'false'
    volumeHandle: 0001-0024-a05891f1-8170-4f0b-bcc0-37ccbfdf1f69-0000000000000005-4267fd51-a03e-4182-94fe-72436d4ac24d
